### ISSUE TITLE
表格单元格里面支持超链接link吗

### ISSUE THREAD

**Issue by hongwingkai** [fasionchan/py-html-table#1]

**Comment by fasionchan** [comment]
可以，你可以将a标签作为数据传进去

**Comment by hongwingkai** [comment]
> 可以，你可以将a标签作为数据传进去

**Comment by hongwingkai** [comment]
标签作为值传进去，尖括号会转义，导致显示不了

**Comment by yafei-sh** [comment]
有个笨办法，将生成的html字符串整体replace处理下'&lt;'、'&gt;'

**Comment by fasionchan** [comment]
@hongwingkai  应该不会转义，除非传给HTMLTable前就转义了

**Comment by hongwingkai** [comment]
@fasionchan 我可以提交代码吗？转义问题可以修改源码解决

**Comment by fasionchan** [comment]
@hongwingkai 可以哈

**Comment by hongwingkai** [comment]
@fasionchan  没有建分支的权限

**Comment by zhaotongdong** [comment]
@hongwingkai 你好，请问你怎么解决的转义字符的问题呀

**Comment by fasionchan** [comment]
转义问题我已经加参数解决了，可以参考另一个issue  #4
