### ISSUE TITLE
你好，请问这个包有anaconda2版本的嘛，公司服务器上是anaconda2版本用这个包报错了~

### ISSUE THREAD

**Issue by pfw2sxx1314** [fasionchan/py-html-table#2]

**Comment by fasionchan** [comment]
你是指在Python 2中报错吗？

**Comment by pfw2sxx1314** [comment]
对的，报错信息如下：
![image](https://user-images.githubusercontent.com/56117264/97252647-759d8680-1845-11eb-95af-c89e4c4e342e.png)

**Comment by fasionchan** [comment]
这个包是在一个Python 3项目中开发的，确实没有考虑对Python 2的兼容性，等我有空会修复。你如果急着用的话，可以将代码clone到本地，将几处不兼容Python 2的写法修改一下即可。

**Comment by pfw2sxx1314** [comment]
好的，等你有空修复下吧，感谢。个人能力有限，昨天看了下不知道咋改~

**Comment by fasionchan** [comment]
不会支持python2了
