### ISSUE TITLE
Can I insert image in the table?

### ISSUE THREAD

**Issue by jamesleo** [fasionchan/py-html-table#4]
I tried to insert an image into the table cell, but failed.
And the image runs fine outside of the table
Would you please to show a sample to insert one picture in the table?

Thanks

**Comment by jamesleo** [comment]
Yes there is a bug,  < > " be converted to &quot,&gt .... in the table cell

**Comment by fasionchan** [comment]
> Yes there is a bug, < > " be converted to &quot,&gt .... in the table cell

Actually, it's a feature, to protect html cell tags. I'll try to add a parameter to disable it.

**Comment by fasionchan** [comment]
parameter escape_cll added.

```
# use case ① not escape any cell
table = HTMLTable(caption='果园收成表', escape_cell=False)
table.add_data_rows(rows)

# use case ② not escape give rows
table = HTMLTable(caption='果园收成表')
table.add_header_rows(rows, escape_cell=False)
table.add_data_rows(rows, escape_cell=False)
table.add_rows(rows, escape_cell=False)
```
